version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # adjust if your Gradle build is in a subdirectory
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    # assignees:
    #   - "crazo7924"

  - package-ecosystem: "github-actions"  # enable updates for GH Actions used in workflows
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"